# Generated by Django 2.0.4 on 2018-04-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('category', models.IntegerField(choices=[(1, 'Góry'), (2, 'Podróże zagraniczne'), (3, 'Makro'), (4, 'Inne')])),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
