# Generated by Django 2.0.4 on 2018-05-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20180505_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.IntegerField(choices=[(1, 'Góry'), (2, 'Podróże zagraniczne'), (3, 'Makro')]),
        ),
    ]
