# Generated by Django 2.0.4 on 2018-05-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20180505_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='aspect_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
