# Generated by Django 2.0.4 on 2018-05-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photo_aspect_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='capture_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
