# Generated by Django 2.0.4 on 2018-05-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_photo_capture_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='aspect_ratio',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
