# Generated by Django 2.0.4 on 2018-05-08 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20180508_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='capture_time',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Photo'),
        ),
        migrations.DeleteModel(
            name='PhotoExif',
        ),
    ]
